################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.c 

OBJS += \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.o \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.o \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.o \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.o 

C_DEPS += \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.d \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.d \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.d \
./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.c Drivers/BSP/Components/VL53L5CX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.c Drivers/BSP/Components/VL53L5CX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.c Drivers/BSP/Components/VL53L5CX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.c Drivers/BSP/Components/VL53L5CX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-Components-2f-VL53L5CX

clean-Drivers-2f-BSP-2f-Components-2f-VL53L5CX:
	-$(RM) ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.cyclo ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.d ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.o ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_api.su ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.cyclo ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.d ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.o ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_detection_thresholds.su ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.cyclo ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.d ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.o ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_motion_indicator.su ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.cyclo ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.d ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.o ./Drivers/BSP/Components/VL53L5CX/vl53l5cx_plugin_xtalk.su

.PHONY: clean-Drivers-2f-BSP-2f-Components-2f-VL53L5CX

