################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_comm.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_network.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_sensor.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/main.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/stm32f4xx_it.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/syscalls.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/sysmem.c \
C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/system_stm32f4xx.c 

OBJS += \
./Application/NUCLEO-F401RE/Src/app_comm.o \
./Application/NUCLEO-F401RE/Src/app_network.o \
./Application/NUCLEO-F401RE/Src/app_sensor.o \
./Application/NUCLEO-F401RE/Src/main.o \
./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.o \
./Application/NUCLEO-F401RE/Src/stm32f4xx_it.o \
./Application/NUCLEO-F401RE/Src/syscalls.o \
./Application/NUCLEO-F401RE/Src/sysmem.o \
./Application/NUCLEO-F401RE/Src/system_stm32f4xx.o 

C_DEPS += \
./Application/NUCLEO-F401RE/Src/app_comm.d \
./Application/NUCLEO-F401RE/Src/app_network.d \
./Application/NUCLEO-F401RE/Src/app_sensor.d \
./Application/NUCLEO-F401RE/Src/main.d \
./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.d \
./Application/NUCLEO-F401RE/Src/stm32f4xx_it.d \
./Application/NUCLEO-F401RE/Src/syscalls.d \
./Application/NUCLEO-F401RE/Src/sysmem.d \
./Application/NUCLEO-F401RE/Src/system_stm32f4xx.d 


# Each subdirectory must supply rules for building sources it contributes
Application/NUCLEO-F401RE/Src/app_comm.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_comm.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/app_network.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_network.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/app_sensor.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/app_sensor.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/main.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/main.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/stm32f4xx_it.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/stm32f4xx_it.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/syscalls.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/syscalls.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/sysmem.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/sysmem.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/NUCLEO-F401RE/Src/system_stm32f4xx.o: C:/Users/bachirin/OneDrive\ -\ STMicroelectronics/Desktop/stm32ai-modelzoo-main\ (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Src/system_stm32f4xx.c Application/NUCLEO-F401RE/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -c -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/Network/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Application/NUCLEO-F401RE/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Middlewares/ST/STM32_AI_Runtime/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/Components/VL53L5CX" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/BSP/NUCLEO-F401RE" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/bachirin/OneDrive - STMicroelectronics/Desktop/stm32ai-modelzoo-main (2)/stm32ai-modelzoo-main/hand_posture/getting_started/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-NUCLEO-2d-F401RE-2f-Src

clean-Application-2f-NUCLEO-2d-F401RE-2f-Src:
	-$(RM) ./Application/NUCLEO-F401RE/Src/app_comm.cyclo ./Application/NUCLEO-F401RE/Src/app_comm.d ./Application/NUCLEO-F401RE/Src/app_comm.o ./Application/NUCLEO-F401RE/Src/app_comm.su ./Application/NUCLEO-F401RE/Src/app_network.cyclo ./Application/NUCLEO-F401RE/Src/app_network.d ./Application/NUCLEO-F401RE/Src/app_network.o ./Application/NUCLEO-F401RE/Src/app_network.su ./Application/NUCLEO-F401RE/Src/app_sensor.cyclo ./Application/NUCLEO-F401RE/Src/app_sensor.d ./Application/NUCLEO-F401RE/Src/app_sensor.o ./Application/NUCLEO-F401RE/Src/app_sensor.su ./Application/NUCLEO-F401RE/Src/main.cyclo ./Application/NUCLEO-F401RE/Src/main.d ./Application/NUCLEO-F401RE/Src/main.o ./Application/NUCLEO-F401RE/Src/main.su ./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.cyclo ./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.d ./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.o ./Application/NUCLEO-F401RE/Src/stm32f4xx_hal_msp.su ./Application/NUCLEO-F401RE/Src/stm32f4xx_it.cyclo ./Application/NUCLEO-F401RE/Src/stm32f4xx_it.d ./Application/NUCLEO-F401RE/Src/stm32f4xx_it.o ./Application/NUCLEO-F401RE/Src/stm32f4xx_it.su ./Application/NUCLEO-F401RE/Src/syscalls.cyclo ./Application/NUCLEO-F401RE/Src/syscalls.d ./Application/NUCLEO-F401RE/Src/syscalls.o ./Application/NUCLEO-F401RE/Src/syscalls.su ./Application/NUCLEO-F401RE/Src/sysmem.cyclo ./Application/NUCLEO-F401RE/Src/sysmem.d ./Application/NUCLEO-F401RE/Src/sysmem.o ./Application/NUCLEO-F401RE/Src/sysmem.su ./Application/NUCLEO-F401RE/Src/system_stm32f4xx.cyclo ./Application/NUCLEO-F401RE/Src/system_stm32f4xx.d ./Application/NUCLEO-F401RE/Src/system_stm32f4xx.o ./Application/NUCLEO-F401RE/Src/system_stm32f4xx.su

.PHONY: clean-Application-2f-NUCLEO-2d-F401RE-2f-Src

