general:
  project_name: handposture
  logs_dir: logs
  saved_models_dir: saved_models
train_parameters:
  batch_size: 32
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.01
  learning_rate_scheduler: reducelronplateau
dataset:
  name: ST_handposture_dataset
  class_names:
  - None
  - Like
  - Dislike
  - FlatHand
  - Fist
  - Love
  - BreakTime
  - CrossHands
  training_path: datasets\ST_VL53L5CX_handposture_dataset
  validation_path: datasets\ST_VL53L5CX_handposture_test
  test_path: null
pre_processing:
  Max_distance: 350
  Min_distance: 150
  Background_distance: 120
data_augmentation:
  RandomFlip: horizontal
model:
  model_type:
    name: CNN2D_ST_HandPosture
    version: v1
  input_shape:
  - 8
  - 8
  - 2
  dropout: 0.5
stm32ai:
  optimization: balanced
  footprints_on_target: null
  path_to_stm32ai: C:/Work/AI/Cube.AI/7.3.0/windows/stm32ai.exe
mlflow:
  uri: ./mlruns
